### ISSUE TITLE
Specify `ecmaVersion` in base config

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/eslint-config#133]
Our configuration generally assumes that ES2017 is being used. We should specify this in the config directly, rather than requiring this to be set in each repository.

**Comment by Gudahtt** [comment]
We had chosen ES2017 because of [this issue](https://github.com/jquery/esprima/issues/1927), which has broken our build in the past.

We haven't needed to work around this in our extension build since this PR, but I don't understand why :thinking:. I know we still use Esprima, and it still doesn't support object spread in all cases, but I don't know which specific cases or why this ceased to be an issue for us.

Worst case, if we use ES2018 in a library we may find an incompatibility and have to add a transpile step for that library in the extension repo.

**Comment by rekmarks** [comment]
Ah, I should've mentioned that we should compile down to ES2017 in our TypeScript projects. The module template repo will also as the source of truth for that?

In other news, isn't Esprima basically completely unmaintained?

**Comment by rekmarks** [comment]
I think ES2020 is the latest stable version to target via TypeScript (and eslint), so that's probably our best bet? The next thing to do would be ESNext, IIRC.

> Yes, it is.

Boo, hiss. On that note, I learned the other day that [ESLint forked Esprima](https://github.com/eslint/espree) with the intention of making it as easy to migrate as possible, answering my long-standing question of "What did people replace Esprima with?". Oh well.
