### ISSUE TITLE
Change Prettier quote-props to as-needed

### ISSUE THREAD

**Issue by shanejonas** [MetaMask/eslint-config#175]
We should disable [quote-props](https://eslint.org/docs/rules/quote-props)

**Comment by brad-decker** [comment]
here here, Its so weird to me that they have to be the same... If it could be universally enforced where removing quotes is true but adding quotes is not i'd be in favor of that. I just don't like quoting things that don't need them :P

**Comment by shanejonas** [comment]
`consistent-as-needed` maybe instead of disabling?

**Comment by rekmarks** [comment]
I initially added `consistent` over `as-needed`. I'm not gonna die on this hill, but here's the argument:

1. It's aesthetically superior. (see below)
2. It's _slightly_ more readable, in that if prop quotations aren't consistent, you're effectively adding different highlights/emphasis to different props, for no reason. (again, see below)
3. Nobody has to quote anything they don't want to; Prettier handles the formatting for us.
4. We've already started using `consistent`, and we don't have a compelling reason to go back.

<img src="https://user-images.githubusercontent.com/25517051/116471772-eee45900-a829-11eb-93f0-7dc36549b81e.png" width=300/>
<img src="https://user-images.githubusercontent.com/25517051/116471943-1c310700-a82a-11eb-810c-a698ba4a7aaf.png" width=300/>

**Comment by rekmarks** [comment]
I'll put up a PR to go back to `as-needed` if the majority supports doing so, but the majority of the feedback so far amounts to "I'm not used to this", and I'd feel a lot better about going back if there were stronger arguments in favor of doing so.

**Comment by brad-decker** [comment]
Your example shows a case where only one argument is without quotes, and in my opinion, is the very crucible of this issue. Converting every property of an object to use quotes because one *must* use them is why consistent is annoying and doesn't Lead to aesthetically pleasing code IMO.
It's not that i'm just not used to it, and if we must use this I am
Happy it's done for me. But the resulting output isn't clearly superior *to me*.

**Comment by brad-decker** [comment]
Also, not that I'm like bothered by it, but to put up a counterpoint to the "we are already using it" part -- did we discuss the impact of that change prior to using it? I think I might have reviewed the PR but overlooked the impact of it. I can't recall but it seems like a bad precedent to set to give points to something because it already exists.
I can think of a few patterns we have in our code base whose existence should not be viewed as a vote of confidence. 😁😬

**Comment by brad-decker** [comment]
<details>
<summary>Only one property forces all others to have quotes</summary>
<img src="https://user-images.githubusercontent.com/4448075/118667898-ff00b000-b7b9-11eb-9136-e0c8c852f3b1.png" />



</details>

**Comment by Gudahtt** [comment]
Aside from subjectively disliking how it looks, the main reason I dislike it is because of diff noise.

Like in the example Brad just gave, the act of adding that single property (`data-testid`) would cause all of those lines to get updated. And similarly removing it would have the same effect.

We have trailing commas partially to reduce diff noise, and the same advantage applies here I think.
