### ISSUE TITLE
Dependencies not included when importing @metamask/eslint-config

### ISSUE THREAD

**Issue by kumavis** [MetaMask/eslint-config#69]
since all the deps are listed as devDeps here, you dont get them when you add `@metamask/eslint-config` in your project

**Comment by Gudahtt** [comment]
This was intentional - instructions on how to add this config are in the README. Different configurations require different sets of plugins, so none of them are included by default.

Though, we should at least have `eslint` as a `peerDependency` :thinking:. That seems appropriate, and is in-line with the [ESLint docs on shareable configs](https://eslint.org/docs/developer-guide/shareable-configs.html). We could add the single required plugin (`eslint-plugin-import`) as a peer dependency as well.

Unfortunately I don't think there is any way to tell `npm` about the other dependencies. Documentation will have to suffice.

**Comment by Gudahtt** [comment]
`peerDependencies` have been added in #70. I think this is as good as we'll get so long as we have multiple configurations in one repo. Short of making this a monorepo anyway.

This seems OK for now, particularly where this is mainly intended for internal use. The documentation makes it easy to use.
